version: "3.1"

services:
  db:
    image: mysql
    volumes:
      - ./mysql-data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cs531

    ports:
      - 3306:3306
